package ${package};

import com.yrxd.commons.web.annotations.Table;
import com.yrxd.commons.web.annotations.PrimaryKey;
import com.yrxd.commons.web.annotations.Column;
<#if (table.hasDateColumn)>
import java.util.Date;
</#if>
<#if (table.hasBigDecimalColumn)>
import java.math.BigDecimal;
</#if>

/**
 * <p>实体类</p>
 * <p>Table: ${table.tableName}</p>
 *
 * @since ${.now} Generated by JunxPlugin
 */
 
@Table(tableName="${table.tableName}",tableComment="${table.tableComment!}")
public class ${table.className} {
	
<#list table.primaryKeys as column>
    @PrimaryKey
    @Column(name="${column.columnName}", type="${column.jdbcTypeName}", length="${column.size}", nullable="${column.nullable?c}", comment="${column.remarks!}")
    private ${column.javaType} ${column.javaProperty};
    
</#list>
<#list table.baseColumns as column>
    @Column(name="${column.columnName}", type="${column.jdbcTypeName}", length="${column.size}", nullable="${column.nullable?c}", comment="${column.remarks!}")
    private ${column.javaType} ${column.javaProperty};	
    
</#list>

<#list table.primaryKeys as column>
    public ${column.javaType} ${column.getterMethodCamelName}(){
        return this.${column.javaProperty};
    }

    public void ${column.setterMethodCamelName}(${column.javaType} ${column.javaProperty}){
        this.${column.javaProperty} = ${column.javaProperty};
    }
</#list>

<#list table.baseColumns as column>
    public ${column.javaType} ${column.getterMethodCamelName}(){
        return this.${column.javaProperty};
    }

    public void ${column.setterMethodCamelName}(${column.javaType} ${column.javaProperty}){
        this.${column.javaProperty} = ${column.javaProperty};
    }
</#list>
}