package ${packName};

<#if importDate == true>
import java.util.Date;
</#if>
<#if importTime == true>
import java.sql.Timestamp;
</#if>
<#if importBigsem == true>
import java.math.BigDecimal;
</#if>

/**
 *
 * @since ${.now} Generated by JunxPlugin
 */
 
public class ${className} {
	
	<#list colum as col>
	/**${col.desc}*/
	private ${col.fieldType} ${col.properName};
	
	</#list>

	<#list colum as col>
	public void set${col.method}(${col.fieldType} ${col.properName}) {
		this.${col.properName} = ${col.properName};
	}
	
	public ${col.fieldType} get${col.method}() {
		return  ${col.properName};
	}
	
	</#list>
}